# Generated by Django 2.1.7 on 2019-03-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('albumId', models.IntegerField()),
                ('albumTitle', models.CharField(max_length=200)),
                ('runtimeSeconds', models.IntegerField()),
                ('runtimeMinutes', models.IntegerField()),
            ],
        ),
    ]
