# Generated by Django 2.1.7 on 2019-03-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190322_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='runtime',
        ),
        migrations.RemoveField(
            model_name='track',
            name='runtime',
        ),
        migrations.AddField(
            model_name='album',
            name='runtime_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='album',
            name='runtime_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='runtime_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='runtime_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='releaseDate',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='ReleaseDate',
        ),
        migrations.DeleteModel(
            name='Runtime',
        ),
    ]
