# Generated by Django 2.1.7 on 2019-03-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190322_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='price',
            field=models.FloatField(default=5.99),
        ),
        migrations.AlterField(
            model_name='track',
            name='price',
            field=models.FloatField(default=0.99),
        ),
    ]
