# Generated by Django 2.1.7 on 2019-03-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user'),
        ('api', '0006_purchase'),
    ]

    operations = [
    ]
