# Generated by Django 2.1.7 on 2019-04-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20190326_1914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='album',
            name='album_art',
            field=models.ImageField(default='uploads/albumaart/default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='track',
            name='mp3',
            field=models.FileField(default='uploads/songs/null.mp3', upload_to=''),
        ),
    ]
